#!/data/data/com.termux/files/usr/bin/bash

PERCY_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PERCY_RUN_DIR="${PERCY_ROOT_DIR}/.run"
PERCY_PORT="${PORT:-8787}"
PERCY_ACCESS_HOST="${PERCY_ACCESS_HOST:-127.0.0.1}"
PERCY_PUBLIC_URL="${PERCY_PUBLIC_URL:-http://${PERCY_ACCESS_HOST}:${PERCY_PORT}}"
PERCY_LIVEZ_URL="${PERCY_LIVEZ_URL:-${PERCY_PUBLIC_URL}/api/livez}"
PERCY_READYZ_URL="${PERCY_HEALTH_URL:-${PERCY_PUBLIC_URL}/api/readyz}"
